// src/routes/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { base } from '$app/paths';
	import { themes } from '$lib';
	import '$css/themes.css';
	import '$css/css.css';
	const fonts = ['Argon', 'Neon', 'Xenon'];
	const randoTheme = themes[Math.floor(Math.random() * themes.length)];
	const randoFont = fonts[Math.floor(Math.random() * fonts.length)];
	onMount(async () => {
		await import('$lib/theme-selector');
	});
	const res = {
		jobz: {
			'Newberry Library': {
				dates: ['2019', 'present'],
				duties: [
					'Provided data scripting support for a major Digital Asset Management System upgrade, extracting, transforming, and loading the library’s 1.5 million complex data records.',
					'Maintained the web infrastructure for the Library’s digital initiatives and programs, including server migrations, database administration, and revitalizations of decades-old content.',
					'Spearheaded the transition to a cloud-first infrastructure model; providing much-needed relief from resource limitations; implemented DevOps strategies throughout digital workflows.',
					'Full stack development lead on numerous digital humanities projects, helping scholars and students create engaging experiences, portals, galleries, and exhibits.',
					"Developed tools, scripts, and projects to provide walkways over the library's weaknesses, improving emphasizing future planning, interoperability, and readability."
				]
			},
			'Chicago Public Library': {
				dates: ['2017', '2020'],
				duties: [
					'Served as project manager for the large-scale digitization projects of rare and delicate Special Collections materials. ',
					'Collaborated with reference librarians to develop tools to help them use their data side-projects to aid their patrons: ',
					'Transformed a 20-year-old Access database on an air-gapped computer into a searchable web front end usable at the reference desk on a USB drive.',
					'Reworked a complex and jury-rigged excel & VBA-based workflow, that allowed a librarian to post her work on the Library’s CMS, to a much more standard csv-to-JSON-to-HTML script.',
					"Created the CPL Digital Collections website, using React, PHP, and Jekyll, integrating seamlessly with the library's CMS, ILS, and other enterprise software.",
					"Developed security and digital forensics workflows used for 'born digital' acquisitions to the four Special Collections in the CPL system."
				]
			},
			'Freelance Data Consulting & Web Development': {
				dates: ['2014', '2017'],
				duties: [
					'Provided consulting, in the form of presentations and analysis reports, for data projects, from how to manage sliding-scale sizing in clothing data, to the benefits and drawbacks of various PIMs and search engines (including SOLR, ElasticSearch).',
					'Provided strategy recommendations for large-scale ETL projects.',
					'Developed new websites and revitalized old ones using PHP and JavaScript (Angular and jQuery).'
				]
			},
			'Codifyd (previously BMI)': {
				dates: ['2011', '2014'],
				duties: [
					'Led teams of data modelers and data analysts to build metadata schemas for large B2B companies (MSC, RS Components), sculpting custom models for a wide range of products, many of which had life-or-death data precision and accuracy needs.',
					'Consulted for clients all over the US and the UK on data strategy, delivering presentations to small C-Level groups and entire company “all staffs.”',
					'Served as a sales engineer, providing client-facing “back end” communication to speak directly to clients’ tech teams.',
					'Served on the R&D team, providing expertise and datasets for software testing for data software; used this time to transition my expertise from “simply data” to actual coding.'
				]
			}
		},
		skillz: {
			'Scripting and development': [
				'Python, JavaScript (React JS, Svelte JS). ',
				'MySQL, PostgreSQL,SQLite, Redis, Apache, Nginx.',
				'Linux, Bash & Zsh, Infrastructure-as-Code, CI/CD (via GitHub, Vercel, Supabase, AWS).'
			],
			'Team lead experience': [
				'Coaching and training of junior developers. ',
				'Led teams of data nerds to delivering millions of clean data records each year.',
				'Provide expertise on infrastructure and platform (ie tech) to aid management decision-making.'
			]
		},
		pubz: [
			[
				[
					'“Movement and Place in Mapping Movement” (Article, 2023) ',
					'https://medium.com/@nick33white/design-theory-movement-and-place-in-mapping-movement-375110749b73'
				],
				[
					'“Marble Runs, Clown Cars, and Metadata Schemas” (DLF Conference Presentation, 2023) ',
					''
				],
				[
					'“The Collective Wisdom Handbook” (Book, 2021) ',
					'https://collectivewisdomproject.org.uk'
				],
				['“IIIF and the Problem with CSS Image Cropping” (Article, 2019) ', ''],
				['“The Time Machine” (Chicago Code4Lib Conference Presentation, 2019)', '']
			],
			[
				['“FOSS: What and Why” (2020)', ''],
				['“Digital Humanities Careers” (2021)', ''],
				['“From Socrates to Stack Exchange: Why Share Knowledge” (2022)', '']
			]
		],
		intz: {
			'Technology ':
				'Enthusiastic about keeping up with technological trends and innovations; engaged with the community to learn how people are leveraging new technologies in legacy and critical codebases, whether that’s understanding the most recent security breaches (omg xz!), or building web components for library assets. ',
			'Music ':
				'Eclectic tastes from 50s jazz to Simpsonwave, from to Afrofuture funk to shoegaze. ',
			'Arts & Literature ':
				'Perpetually engaged with non-representational theory (Gilles Deleuze, Guy Debord) and immersed in the phenomenology of literature (J.L. Borges), art (Maurice Blanchot), and life (Alphonso Lingis).'
		}
	};
</script>

<div class="bg"></div>
<main style="--rando-font: {randoFont}">
	<article>
		<section class="title-section">
			<div class="title-text">
				<h4 class="title-top">a little</h4>
				<h3 class="title">Resume</h3>
				<h4 class="title-bottom">for</h4>
				<h1 class="name">Nick White</h1>
			</div>
		</section>
		<section class="body-text">
			<h2>Employment History</h2>
			<dl>
				{#each Object.keys(res.jobz) as job}
					<dt>{job}</dt>
					<dd class="dates">
						{res.jobz[job].dates[0]} -
						{res.jobz[job].dates[1]}
					</dd>
					{#each res.jobz[job].duties as dut}
						<dd>{dut}</dd>
					{/each}
				{/each}
			</dl>
		</section>
		<section class="body-text">
			<h2>Skills</h2>
			<dl>
				{#each Object.keys(res.skillz) as skillset}
					<dt>{skillset}</dt>
					{#each res.skillz[skillset] as skill}
						<dd>{skill}</dd>
					{/each}
				{/each}
			</dl>
		</section>
		<section class="body-text">
			<h2>Publications &amp; Presentations</h2>

			<dl>
				{#each res.pubz as pubset, i}
					<dt>
						{#if i === 0}
							Articles &amp; Conferences
						{:else}
							Job Talks
						{/if}
					</dt>

					{#each pubset as pub}
						<dd>
							{#if pub[1]}
								<a href={pub[1]} target="_blank">{pub[0]}</a>
							{:else}
								{pub[0]}
							{/if}
						</dd>
					{/each}
				{/each}
			</dl>
			<p>
				<a href="https://nick3white.github.io/portfolio" target="_blank"
					>Please enjoy this clickable anchor tag which will carry you off to see a portfolio of the
					web dev work I've done recently, too.</a
				>
			</p>
		</section>
		<section class="body-text">
			<h2>Interests</h2>
			<dl>
				{#each Object.entries(res.intz) as int}
					<dt>{int[0]}</dt>
					<dd>{int[1]}</dd>
				{/each}
			</dl>
		</section>
    <div class="citation">
      <p>
Wallpaper artists are all in their filenames.  If there's no indication where it came from in the filename, it's because I don't know where it came from. :(
      </p>
      <p>
      They're mostly by Masashi Wakui.
      </p>
    </div>
	</article>
</main>

<theme-selector {themes} defaultTheme={randoTheme}></theme-selector>

<style>
	main {
		color: rgb(var(--foreground));
		display: flex;
		flex-direction: column;
		justify-content: start;
		align-items: center;
		font-family: var(--rando-font);
		position: relative;
		backdrop-filter: blur(10px);
	}
	.bg {
		background-image: var(--wallpaper);
		background-size: cover;
		background-position: center;
		z-index: 0;
		content: '';
		position: fixed;
		top: 0;
		right: 0;
		bottom: 0;
		left: 0;
	}
	article,
	.title-section {
		background-image: var(--wallpaper);
		background-position: center;
		background-size: cover;
		background-attachment: fixed;
	}
	article {
		padding-block: 22rem;
    position: relative;
		width: min(555px, 90vw);
	}
	.body-text,
	.title-text, .citation {
		background: rgba(var(--background), 0.87);
		backdrop-filter: blur(10px) saturate(3.3);
	}
	.title-section {
		height: 22rem;
		position: sticky;
		top: -11rem;
		z-index: 10;
	}
	.title-text {
		position: sticky;
		top: -1rem;
		padding: 0 2rem 1rem 2rem;
		margin: 0;
		& .title-top,
		.title,
		.title-bottom,
		.name {
			margin-block: 0;
		}
		.title-top {
			margin-inline: 2rem;
		}
		.title-bottom {
			margin-inline: 3rem;
		}
		.title {
			margin-inline: 1rem;
		}
	}
	.name,
	.title {
		position: sticky;
	}
	.name {
		margin-bottom: 10px !important;
		top: 3rem;
		font-size: clamp(1.25rem, -0.2875rem + 6.8333vw, 3.3rem);
	}
	.title {
		top: 7rem;
		font-size: clamp(1rem, 0.625rem + 1.6667vw, 1.5rem);
	}
	.body-text {
		margin-bottom: 76px;
		padding-bottom: 11px;
	}
	h2,
	dt {
		position: sticky;
		padding-inline: 2rem;
		margin: 0;
		background: rgba(var(--color7));
		color: rgba(var(--color0));
	}
	h2 {
		top: 11rem;
	}
	dt {
		top: 13rem;
	}
	.dates {
		position: sticky;
		padding-inline: 2rem;
		margin: 9px 0;
		top: 14.3rem;
		backdrop-filter: blur(20px);
	}
	dd:not(.dates) {
		font-size: 1.1rem;
		line-height: 2rem;
		border-inline: 2px solid rgba(var(--color3), 0.5);
		margin: 2rem 1rem;
		padding: 0 1rem;
	}
	.body-text p {
		font-size: 1.1rem;
		line-height: 2rem;
		margin: 2rem 1rem;
		padding: 0 1rem;
	}
	.body-text :is(p, dd):has(a) {
		background-image: linear-gradient(
			to right,
			rgba(var(--foreground), 0.1) 0 50%,
			rgba(var(--foreground), 0.2) 50% 100%
		);
		background-size: 200% 100%;
		background-position: -100% 0;
		transition: 200ms;
	}
	.body-text :is(p, dd):has(a):hover {
		background-position: 0 0;
	}
	.body-text a {
		display: inline-block;
		height: 100%;
		width: 100%;
		text-decoration: none;
		color: inherit;
	}
	.body-text a:hover {
	}
	img {
		width: 100%;

		padding-inline: 2rem;
		object-fit: contain;
	}
	img {
		margin-bottom: 33px;
	}
  .citation {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    padding: 11px;
    display: flex;
    flex-direction: column;
    gap: 11px;
& p {
      padding: 0;
      margin: 0;
    }
  }
</style>

// src/routes/index.tsx
import { component$, type JSXNode } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { css } from "~/styled-system/css";
import Halloween from "~/media/halloween.png?jsx";
import RaceBeforeRace from "~/media/rb4r.png?jsx";
import MappingMovement from "~/media/mapping-movement.png?jsx";

type SocialMediaLink = {
    platform: string;
    url: string;
};

const socialMediaLinks: SocialMediaLink[] = [
    {
        platform: "linkedin",
        url: "https://www.linkedin.com/in/nick-white-511000288/",
    },
    {
        platform: "medium",
        url: "https://medium.com/@nick33white",
    },
    {
        platform: "github",
        url: "https://github.com/nick3white/",
    },
    {
        platform: "codepen",
        url: "https://codepen.io/nick3white",
    },
];
const skills: [string, string[]][] = [
    ["JavaScript", ["Svelte", "React", "Qwik", "Node", "(and many more)"]],
    ["Data & Scripting", ["Python", "Pandas", "Bash"]],
    [
        "Dev Ops / Sysadmin",
        ["Linux", "Apache / LAMP", "IaC, IaaS, BaaS", "CI/CD"],
    ],
    ["Database", ["MySQL", "PostgreSQL", "Prisma", "Redis"]],
];
type Publication = {
    title: string;
    type: string;
    year: number;
    description: string;
    url?: string;
};

const publications: Publication[] = [
    {
        title: "Movement and Place in Mapping Movement",
        type: "Article",
        year: 2023,
        description:
            "In the development of the Mapping Movement rebuild, I used place and movement to recreate something of the book-experience, while also evoking the spirit of the Mapping Movement project.",
        url: "https://medium.com/@nick33white/design-theory-movement-and-place-in-mapping-movement-375110749b73",
    },
    {
        title: "Marble Runs, Clown Cars, and Metadata Schemas",
        type: "Conference Presentation, Digital Library Federation 2023 Forum",
        year: 2023,
        description:
            "Described the flow of data from legacy systems to new ones, using a 'value first' approach (marble run) in a multiply-redundant data environment, the problem with validating values (clown car), and the improvements available using an 'attribute first' approach",
    },
    {
        title: "The Collective Wisdom Handbook",
        type: "Book",
        year: 2021,
        description:
            "Covers the history, practice, best practices, and technology used crowdsourcing transcriptions in cultural heritage institutions. Written by me and 20 of my closest friends.",
    },
    {
        title: "IIIF and the Problem with CSS Image Cropping",
        type: "Article",
        year: 2019,
        description:
            "Explains the challenges of CSS image handling and how to use IIIF to solve them.",
        url: "https://medium.com/@digitalnewberry/iiif-and-the-problem-with-css-image-cropping-651cfeb5593b",
    },
    {
        title: "FOSS: What and Why",
        type: "Job Talk",
        year: 2020,
        description:
            "Overview of what FOSS means, what open source is, and their value, both ethically and practically",
    },
    {
        title: "Digitial Initiatives Career Talk",
        type: "Job Talk",
        year: 2021,
        description:
            "Presented to a number of college classes, a summary of what we do and how we do it.",
    },
    {
        title: "From Socrates to Stack Exchange",
        type: "Job Talk",
        year: 2022,
        description:
            "Covering the general applications and use cases of various languages, covering Bash (and Linux generally), Python, and JavaScript",
    },
    {
        title: "The Time Machine",
        type: "Conference Presentation, Code4Lib Chicago",
        year: 2019,
        description:
            "Covers technology used for the Time Machine project, from crowdsourcing transcription, to Gatsby & the importance of SSG to libraries",
    },
];
type WorkSample = [string, string, JSXNode];

export default component$(() => {
    const mapmov = <MappingMovement />;
    const hallo = <Halloween />;
    const rb4r = <RaceBeforeRace />;
    const samples: WorkSample[] = [
        [
            "Halloween",
            "https://digital.newberry.org/collection-stories/halloween",
            hallo,
        ],
        ["Race B4 Race", "https://digital.newberry.org/rb4r", rb4r],
        ["Mapping Movement", "https://mappingmovement.newberry.org/", mapmov],
    ];
    return (
        <main
            class={css({
                scrollBehavior: "smooth",
                display: "flex",

                flexDirection: "column-reverse",
                lg: {
                    flexDirection: "row",
                },

                marginInline: "clamp(8px, 1vh, 16px)",
                paddingInline: "clamp(8px, 1vh, 16px)",
                gap: "32px",
                "& aside": {
                    flex: 1,
                    display: "flex",
                    flexDirection: "column",
                    gap: "16px",
                    zIndex: "200",
                    height: "100%",
                    top: "16px",
                    marginInline: "clamp(8px, 1vh, 16px)",
                    // paddingInline: "clamp(8px, 1vh, 16px)",
                    lg: {
                        paddingInline: 0,
                        marginInline: 0,
                    },
                },
                "& h3": {
                    borderBottom: "2px solid  rgba(var(--fg-1), 0.5)",
                    marginBottom: "6px",
                },
                "& article": {
                    position: "relative",
                    flex: 3,
                },
                "& .skill-sublist": {
                    position: "relative",
                    // paddingLeft: "16px",
                    "& dd": {
                        pointerEvents: "none",
                        opacity: 0.001,
                        position: "absolute",
                        top: "100%",
                        left: "4px",
                        padding: "8px",
                        width: "100%",
                        background: "rgb(var(--bg-1))",
                        border: "1px solid rgba(var(--fg-1), 0.5)",
                        zIndex: 100,
                        transition: "250ms",
                    },
                    "& dt:hover + dd": {
                        opacity: 0.99,
                    },
                },
                "& .sample-link": {
                    display: "flex",
                    flexDirection: "column",
                    border: "1px solid rgba(var(--fg-1), 0.5)",
                    marginBottom: "16px",
                    transition: "250ms",
                    "&:hover": {
                        border: "1px solid rgba(var(--fg-1), 1)",
                    },
                },
                "& .sample-link dt": {
                    padding: "0px 8px",
                },
                "& .sample-link dd": {
                    padding: "4px",
                },
                "& .me": {
                    width: "100%",
                },
                "& article h2": {
                    borderBottom: "var(--border)",
                    boxShadow: "var(--shadow-soft)",
                },
                "& dt, dd, .socials li": {
                    marginInline: "clamp(8px, 1vh, 32px)",
                    paddingInline: "clamp(8px, 1vh, 32px)",
                },
                "& dt": {
                    borderBottom: "2px solid rgba(var(--fg-1), 0.3)",
                },
                "& dt, .socials li": {
                    textShadow: "var(--text-shadow-soft)",
                    fontWeight: "bold",
                    fontSize: "1.25rem",
                    marginBlock: "3px",
                },
                "& .socials li": {
                    background:
                        "linear-gradient(to right,rgba(var(--fg-1),.3),rgba(var(--fg-1),.3)),linear-gradient(to right,rgba(var(--fg-1),1),rgba(var(--fg-1),1))",
                    backgroundSize: "100% .1rem,0 .1rem",
                    backgroundPosition: "100% 100%,0 100%",
                    backgroundRepeat: "no-repeat",
                    transition: "background-size .3s",
                    "&:hover": {
                        backgroundSize: "0 .1rem,100% .1rem",
                    },
                },
                "& dd": {
                    border: "1px solid rgba(var(--splash),0.33)",
                    "& em": {
                        paddingRight: "11px",
                        fontStyle: "italic",
                        fontSize: "1.1rem",
                    },
                    "& a": {
                        color: "var(--splash-color-alt)",
                        textShadow: "var(--text-shadow-alt-soft)",
                        transition: "200ms",
                        borderBottom: "var(--text-underline)",
                        "&:hover": {
                            textShadow: "var(--text-shadow-alt)",
                        },
                    },
                },
            })}
        >
            <aside>
                <section class="socials">
                    <h3>Socials</h3>
                    <ul>
                        {socialMediaLinks.map((social) => {
                            // const linkgcc = socialMediaLinks[platform] as string;
                            return (
                                <li key={social.platform}>
                                    <a href={social.url} target="_blank">
                                        {social.platform}
                                    </a>
                                </li>
                            );
                        })}
                    </ul>
                </section>
                <section class="skill-lists">
                    <h3>Skills</h3>
                    <ul>
                        {skills.map((list, idx) => (
                            <li key={`skill-${idx}`} class="skill-sublist">
                                <dl>
                                    <dt>{list[0]}</dt>
                                    <dd>
                                        {list[1].map((li, i) => (
                                            <li key={`subskill-${i}`}>{li}</li>
                                        ))}
                                    </dd>
                                </dl>
                            </li>
                        ))}
                    </ul>
                </section>
                <section class="samples">
                    <h3>Recent Projects</h3>
                    <dl>
                        {samples.map((sample, idx) => (
                            <a
                                key={`sample-${idx}`}
                                class="sample-link"
                                href={sample[1]}
                                target="_blank"
                            >
                                <dt>{sample[0]}</dt>
                                <dd>{sample[2]}</dd>
                            </a>
                        ))}
                    </dl>
                </section>
            </aside>
            <article
                class={css({
                    "& ul, li, h2, h3": {
                        marginInline: "clamp(8px, 1vh, 32px)",
                        paddingInline: "clamp(8px, 1vh, 32px)",
                        listStyleType: "none",
                    },
                    "& h2": {
                        fontSize: "clamp(1.66rem, 6vw, 3rem)",
                        lineHeight: "clamp(1.66rem, 6vw, 3rem)",
                    },
                    "& li": {
                        marginBlock: "8px",
                        border: "1px solid rgba(var(--splash),0.33)",
                    },
                    "& h3": {
                        fontSize: "clamp(1.33rem, 5vw, 2rem)",
                        lineHeight: "clamp(1.33rem, 5vw, 2rem)",
                    },
                })}
            >
                <section>
                    <h2
                        class={css({
                            position: "relative",
                            "& .normo": {
                                fontSize: "clamp(1.66rem, 6vw, 3rem)",
                                lineHeight: "clamp(1.66rem, 6vw, 3rem)",
                                opacity: 0.99,
                                transition: "250ms",
                            },
                            "&:hover .normo": {
                                opacity: 0,
                            },
                            "& .hido": {
                                fontSize: "clamp(0.85rem, 4vw, 2rem)",
                                lineHeight: "clamp(0.85rem, 4vw, 2rem)",
                                display: "flex",
                                justifyContent: "flex-start",
                                alignItems: "center",
                                position: "absolute",
                                top: 0,
                                right: 0,
                                bottom: 0,
                                // left: "clamp(1.77rem, 6vw, 3rem)",
                                opacity: 0,
                                transition: "250ms",
                            },
                            "&:hover .hido": { opacity: 1 },
                        })}
                    >
                        <span class="normo">Developer</span>
                        <span class="hido">Front End + Data Magic</span>
                    </h2>

                    <li>
                        Extensive experience executing designs using JavaScript,
                        React JS, Svelte JS, and more, emphasizing usability,
                        appeal, and accessibility
                    </li>
                    <li>
                        Extensive experience developing utilities and scripts
                        for use in large scale data projects, for both data
                        manipulation and data analysis
                    </li>
                    {/* <li> */}
                    {/*     Experience performing DevOps and Sys Admin tasks */}
                    {/*     including linux server admin, serverless & CI/CD */}
                    {/*     technologies, and maintaining off the shelf software */}
                    {/* </li> */}
                    <li>
                        Jack-of-all-trades tech lead experience: management and
                        maintenance of all the things: Redis, PostgreSQL, MySQL,
                        LAMP stack, CI/CD & serverless, IaaS, BaaS, IaC, etc
                    </li>
                    <li>
                        Experience coaching junior developers and assisting with
                        self-directed education & training
                    </li>
                </section>
                <section>
                    <h2>Work History</h2>

                    <h3>Newberry Library</h3>

                    <li>
                        Built and rebuilt 10+ projects as the principal
                        developer, focusing on replicating the wonderful aspects
                        of traditional library and learning experiences, while
                        still providing novel, innovative experiences.
                    </li>
                    <li>
                        Provided the back end support, through scripting (python
                        & bash) and heavy lifting, for a major DAMS upgrade
                        project, gathering, transforming, manipulating, and
                        massaging millions of records coming from various
                        decaying sources, with an emphasis on reusability - the
                        next DAMS upgrade will be much easier.
                    </li>
                    <li>
                        Maintained the web infrastructure for decades of the
                        Newberry's Digital Initiatives, from server migrations,
                        database administration, and branding overhauls to old
                        projects, to cron jobs to update my Slack status based
                        on time of day. In the last year, I've been transforming
                        the library's digital infrastructure to a cloud-first
                        model; I believe that approach outsources the library's
                        most problematic points of weakness.
                    </li>
                </section>
                <section>
                    <h3>Chicago Public Library</h3>

                    <li>
                        Built bespoke tools for reference librarians to enable
                        them to search and discover their passion projects in
                        order to share the resources, and their passions, with
                        patrons
                    </li>
                    <li>
                        Managed large scale digitization projects from
                        conception to launch, including the grant writing,
                        staffing, and planning in between
                    </li>
                    <li>
                        Created web portals for digital content, from digital
                        collections, to born-digital gifts to the Special
                        Collections, with an emphasis on building rock solid
                        tools that would survive without maintenance, using Ruby
                        and Jekyll SSG tools
                    </li>
                </section>
                <section>
                    <h3>Freelance Web Development & Consulting</h3>
                    <li>
                        Used PHP, CSS, JavaScript (Angular 1.0, jQuery) to
                        develop new websites and rebuilt older ones for various
                        clients, or updated existing ones
                    </li>
                    <li>
                        Consulted with clients from my Codifyd days with whom I
                        had established ongoing relationships; specialized in
                        data remediation, ETL, and how to train data analysts
                    </li>
                </section>
                <section>
                    <h3>Codifyd</h3>

                    <li>
                        Handled data remediation, transformation, and
                        restructuring for large scale data cleanig and ETL
                        projects, delivering millions of cleaned records yearly
                    </li>
                    <li>
                        Consulted nationally and internationally on data
                        science, data architecture, and how to both communicate
                        data, and to listen to it
                    </li>
                    <li>
                        Worked with clients with millions of products and
                        thousands of employees, as well as with companies small
                        scale companies (which were usually more fun!)
                    </li>
                </section>
                <section>
                    <h2>Publications (&amp;c)</h2>
                    <dl>
                        {publications.map((p) => (
                            <>
                                <dt>{p.title}</dt>
                                <dd>
                                    <em>
                                        {p.url ? (
                                            <a
                                                href={p.url}
                                                target="_blank"
                                                class="art-link"
                                            >
                                                {p.type}
                                            </a>
                                        ) : (
                                            p.type
                                        )}
                                        .
                                    </em>
                                    {p.year}. {p.description}
                                </dd>
                            </>
                        ))}
                    </dl>
                </section>
                <section>
                    <h2>Interests</h2>

                    <h3>Technology</h3>
                    <li>
                        <b>Qwik</b> JS has got me thinking about how (and when!)
                        I deliver JS to the client; while it may not make a
                        difference to efficiency (depending on the bundle), but
                        it helps to keep from getting too abstract in my
                        thinking.
                    </li>
                    <li>
                        I've been making websites since they were just HTML, so
                        playing with <b>HTMX</b> reminds me of that era.
                        JavaScript makes it feel like everything is imaginary
                        except JS; HTMX reminds me of the before times.
                    </li>
                    <li>
                        Playing around with <b>Lit</b> - and working with web
                        components generally - feels like you're Gambit from the
                        X-Men. I love their versatility - though, to be honest,
                        I haven't found a great use case in my work.
                    </li>
                </section>
                <section>
                    <h3>Non-Technology</h3>
                    <li>
                        I'm always excited to have conversations about{" "}
                        <b>music</b>. I have pretty wide tastes, from 50s jazz,
                        60s experimental music, 70s dub, 80s hardcore, 90s
                        indie, 00s IDM, to Simpsonwave in the 2010s, there's
                        always something interesting going on.
                    </li>
                    <li>
                        <b>Arts & Literature</b> may seem like they're far
                        afield, but they inform the foundations of my
                        approaches. Non-representational Theory (Gilles Deleuze,
                        Guy Debord) and phenomenology (Maurice Blanchot,
                        Alphonso Lingis) are a couple of specific areas of
                        interest.
                    </li>
                </section>
            </article>
        </main>
    );
});

export const head: DocumentHead = {
    title: "Nick White, Front End Dev",
    meta: [
        {
            name: "description",
            content: "A resume site",
        },
    ],
};
